---

workspace:
  base: /go
  path: src/github.com/packethost/pkg

pipeline:
  lint:
    group: ci
    image: golang:1.12-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - GO111MODULE=on go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - CGO_ENABLED=0 golangci-lint run --disable-all -E errcheck
      - gofmt -d . | (! grep '.')

  test:
    group: ci
    image: golang:1.12
    commands:
      - GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  build:
    group: ci
    image: golang:1.12-alpine
    commands:
      - GO111MODULE=on CGO_ENABLED=0 go build -mod=vendor ./cmd/...

  examplelog:
    group: examples
    image: alpine
    commands:
      - ./examplelog
    environment:
      PACKET_ENV: ci
      PACKET_VERSION: "0"
    secrets: [rollbar_token]

  codecov:
    group: notifications
    image: plugins/codecov
    secrets: [codecov_token]
