---

workspace:
  base: /go
  path: src/github.com/packethost/pkg

pipeline:
  lint:
    group: ci
    image: golang:1.12-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - go get -v -u github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter --errors --vendor --vendored-linters ./...
      - gofmt -d *.go | (! grep '.')

  test:
    group: ci
    image: golang:1.12
    commands:
      - GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  build:
    group: ci
    image: golang:1.12-alpine
    commands:
      - GO111MODULE=on CGO_ENABLED=0 go build -mod=vendor ./cmd/...

  examplelog:
    group: examples
    image: alpine
    commands:
      - ./examplelog
    environment:
      PACKET_ENV: ci
      PACKET_VERSION: "0"
    secrets: [rollbar_token]

  codecov:
    group: notifications
    image: plugins/codecov
    secrets: [codecov_token]
