package log

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

type protoMessageWrapper struct {
	msg proto.Message
}

func (p *protoMessageWrapper) MarshalJSON() ([]byte, error) {
	return protojson.Marshal(p.msg)
}

// ProtoAsJSON performs a type erasure of proto.Message to be embedded into the log fields.
//
// This is a workaround for types generated by protobuf providing a String() method.
// This makes them interpreted by the logger as fmt.Stringer interfaces,
// and flattened to string, rather than, as one would expect, a JSON object.
//
// Example:
//
//	logger = logger.With("my-proto-object", log.ProtoAsJSON(&myProto))
func ProtoAsJSON(message proto.Message) json.Marshaler {
	return &protoMessageWrapper{msg: message}
}
