{
 "title": "DEFINE TITLE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Used memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{service=\"packet-invoice-production-internal-http\"})\n"
    }
   ]
  },
  {
   "title": "requests_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\ngin_requests_total{service=\"packet-invoice-production-internal-http\",url!=\"/_packet/healthcheck\",url!=\"/\",url!=\"/favicon.ico\"}\n\n",
     "legendFormat": "{{method}}{{url}} ({{code}})"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(go_memstats_frees_total{service=\"packet-invoice-production-internal-http\"})\n"
    }
   ]
  },
  {
   "title": "request_duration_seconds_count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gin_request_duration_seconds_count{service=\"packet-invoice-production-internal-http\"}[5m])\n\n",
     "legendFormat": "{{service}}{{version}}"
    }
   ]
  },
  {
   "title": "Process Cpu total (sec)",
   "type": "gauge",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{service=\"packet-invoice-production-internal-http\"}\n  \n"
    }
   ]
  }
 ]
}